name: commit_agent
description:  An AI-powered Git commit assistant that automatically generates commit messages using OpenAI GPT models.
version: 1.0.0
publish_to: "https://pub.dev"    
homepage: https://github.com/rohan-165/commit_agent
repository: https://github.com/rohan-165/commit_agent

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  http: ^1.5.0

executables:
  commit_agent: commit_agent

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
